### ISSUE TITLE
[JOSS Review] API documentation

### ISSUE THREAD

**Issue by CFGrote** [xuanxu/starmatrix#60]
I find the API documentation provided at https://starmatrix.readthedocs.io a bit rudimentary. I'd suggest to document classes and methods (along with  signature and return type) and standalone functions. You're already using docstrings, if you add
```
:param <parameter_name>: <description>
:type   <parameter_name>: <type>
```
to class methods and then add the  [sphinx autodoc extension](https://www.sphinx-doc.org/en/master/usage/extensions/autodoc.html), to the list of extensions in docs/conf.py, you'll have it. This would also activate online documentation in ipython or jupyter interactive environments.

**Comment by xuanxu** [comment]
Yes, this is a great suggestion, and was recommended also by @ygrange during his review. As [I mentioned there](https://github.com/xuanxu/starmatrix/issues/55#issuecomment-1176123328) I'm short on bandwith right now and when I'll work on it depends on how blocking you consider it for the current paper submission.

**Comment by CFGrote** [comment]
Ok I'll close here as #55 addresses the same points.
