### ISSUE TITLE
[JOSS Review]: matrix datastructure

### ISSUE THREAD

**Issue by CFGrote** [xuanxu/starmatrix#63]
I suggest to return the Q matrix not as a plain array but as an [xarray](https://xarray.dev/) with appropriately labeled axes and dimensions. Otherwise every user will have to code up a index-to-element mapping which is a potential source of error that could easily be avoided. Getting the raw array out of an xarray is trivial.

**Comment by xuanxu** [comment]
We currently have this in our roadmap, we plan to add a setting to specify the desired format for the returned data (other than the current Numpy arrays), with hdf5 and xarray among the available options. 

So this is something that should be ready for the 2.0 release, unless you think it is needed for the current version submitted to JOSS, in that case and about a timetible for it I can only refer to my [previous comment](https://github.com/xuanxu/starmatrix/issues/60#issuecomment-1185795311) 😓

**Comment by CFGrote** [comment]
Understand. I'll close here hoping it will be addressed in not too distant future.
